---
title: "PM566 Final Project"
author: "Misha Khan"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my PM566 Final Project website.

<br>

# Lab setup

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px")

```

```{r}
source("pm566-midterm-final-copy.R")

#EDA Crime with the highest count per month
crime_count_month <-  
  crimedat %>%
  group_by(Month, Year, Area) %>% 
  summarize(CrimeCount = n()) 

crime_count_month <- subset(crime_count_month, 
                            Year %in% c("2020", "2021")) #2022 is still in progress

#Order months in order for graph
month.ordered <- 
  crime_count_month %>%
  mutate(Month = factor(Month, levels = c("Jan", "Feb", "Mar", "Apr", "May",  "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")))

month.ordered  %>%
  ggplot(aes(x = Month, y = CrimeCount, fill = Area)) +
  geom_bar(stat = "identity")

#Age, ethnicity, sex
#Create df
victim_demographics <-
  crimedat %>%
  select(`Record No`, `Crime Code`,`Victim Age`, `Victim Sex`, `Victim Ethnicity` , Area, Crime, `Year`)

#For simplicity
victim_demographics <- subset(victim_demographics, 
                              `Victim Sex` %in% c("F", "M") &
                                `Victim Ethnicity`  %in% c("B", "H", "W", "A", "O"))

#Age
victim_demographics %>%
  ggplot(mapping = aes(x = `Victim Age`)) + 
  geom_histogram(position = "identity", alpha = 0.7, binwidth = 1, color = "black", fill = "red") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 20)) +
  ggtitle("Victim Age Distribution") +
  xlab("Age") +
  ylab("Count")

#Sex
victim_demographics %>%
  ggplot(aes(x=`Victim Age`, color= `Victim Sex`)) +
  geom_histogram(fill="white", alpha=0.2, position="identity") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 20)) 

#Ethnicity
victim_demographics <-
  victim_demographics %>%
  mutate(victim_ethnicity_f = case_when(victim_demographics$`Victim Ethnicity` == "W" ~ "White",
                                        victim_demographics$`Victim Ethnicity` == "B" ~ "Black",
                                        victim_demographics$`Victim Ethnicity` == "A" ~ "Asian",
                                        victim_demographics$`Victim Ethnicity` == "H" ~ "Hispanic",
                                        victim_demographics$`Victim Ethnicity` == "O" ~ "Other"))

victim_demographics <-
  victim_demographics %>%
  mutate(victim_age_f = 
           case_when(victim_demographics$`Victim Age` >= 0 & victim_demographics$`Victim Age`<= 10 ~ "0-10",
                     victim_demographics$`Victim Age` >= 11 & victim_demographics$`Victim Age`<= 20 ~ "11-20",
                     victim_demographics$`Victim Age` >= 21 & victim_demographics$`Victim Age`<= 30 ~ "21-30",
                     victim_demographics$`Victim Age` >= 31 & victim_demographics$`Victim Age`<= 40 ~ "31-40",
                     victim_demographics$`Victim Age` >= 41 & victim_demographics$`Victim Age`<= 50 ~ "41-50",
                     victim_demographics$`Victim Age` >= 51 & victim_demographics$`Victim Age`<= 60 ~ "51-60",
                     victim_demographics$`Victim Age` >= 61 & victim_demographics$`Victim Age`<= 70 ~ "61-70",
                     victim_demographics$`Victim Age` >= 71 & victim_demographics$`Victim Age`<= 80 ~ "71-80",
                     victim_demographics$`Victim Age` >= 81 & victim_demographics$`Victim Age`<= 90 ~ "81-90",
                     victim_demographics$`Victim Age` >= 91 & victim_demographics$`Victim Age`<= 100 ~ "91-100"))

victim_demographics %>%
  ggplot(mapping = aes(x = victim_age_f, fill = factor(victim_ethnicity_f))) + 
  geom_bar(position = "dodge") +
  scale_fill_brewer(palette = "Paired") +
  ggtitle("Victim Ethnicity by Age") +
  xlab("Count") +
  ylab("Age") +
  labs(fill = "Victim Ethnicity")

```

```{r}
### LEAFLET MAP PLOT OF CENTRAL 
central_top_crimes <-
  crimedat %>%
  select(`Record No`, `Crime Code`, Area, Crime, `Year`, `Lat`, `Lon`)

#Subset Area = Central and Year = 2021
central_top_crimes <- subset(central_top_crimes, 
                             `Area` %in% c("Central") &
                               `Year` %in% c("2021"))

#View top 5 crimes in Central
central_top_crimes %>% 
  group_by(Area, `Crime Code`, Crime) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>%
  head(,10) %>%
  knitr::kable()

#Now subset Crime Code to top 5 in that area
central_top_crimes <- subset(central_top_crimes, 
                             `Crime Code` %in% c("330", "624", "740", "230", "440"))

#Map color palette
central.pal <- colorFactor(c('red', 'yellow', 'blue', 'green', 'purple'), domain = central_top_crimes$`Crime`)

central_map <- 
  leaflet(central_top_crimes) %>%  
  addProviderTiles('CartoDB.Positron') %>% 
  addCircles(
    lat = ~Lat, 
    lng = ~Lon,
    label = ~paste0(central_top_crimes$`Crime`),
    color = ~ central.pal(central_top_crimes$`Crime`),
    opacity = 0.5,
    fillOpacity = 1,
    radius = 5
  ) %>%
  addLegend('bottomleft', 
            pal = central.pal,  
            values = central_top_crimes$`Crime`,
            title = 'Central Crime Map', 
            opacity = 1)
central_map
```


## Showcasing plots {.tabset}

### Tab 1

```{r echo=FALSE}
central_map
```  

### Tab 2

```{r echo=FALSE}
#victim_demographics
```

## {-}
